INSERT INTO EXAM(ExamName,CourseId) VALUES('Statistics Partial1',(SELECT CourseId FROM (SELECT TOP 1 * FROM Course ORDER BY NEWID()) AS RandomCourse));
INSERT INTO EXAM(ExamName,CourseId) VALUES('Statistics Partial2',(SELECT CourseId FROM (SELECT TOP 1 * FROM Course ORDER BY NEWID()) AS RandomCourse));
INSERT INTO EXAM(ExamName,CourseId) VALUES('Algebra Partial',(SELECT CourseId FROM (SELECT TOP 1 * FROM Course ORDER BY NEWID()) AS RandomCourse));
INSERT INTO EXAM(ExamName,CourseId) VALUES('Algebra Final',(SELECT CourseId FROM (SELECT TOP 1 * FROM Course ORDER BY NEWID()) AS RandomCourse));
INSERT INTO EXAM(ExamName,CourseId) VALUES('Networking Partial',(SELECT CourseId FROM (SELECT TOP 1 * FROM Course ORDER BY NEWID()) AS RandomCourse));
INSERT INTO EXAM(ExamName,CourseId) VALUES('Networking Project',(SELECT CourseId FROM (SELECT TOP 1 * FROM Course ORDER BY NEWID()) AS RandomCourse));

INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (5,5,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (4,6,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (3,4,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (6,7,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (4,8,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (9,10,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (8,5,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (3,8,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (7,8,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (4,4,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (6,9,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (2,3,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (10,10,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (10,6,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (8,10,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));
INSERT INTO ExamResults(GradeNormalSession,GradeRetakeSession,ExamId,StudentId) VALUES (8,7,(SELECT ExamId FROM (SELECT TOP 1 * FROM Exam ORDER BY NEWID()) AS RandomExam),(SELECT StudentId FROM (SELECT TOP 1 * FROM Student ORDER BY NEWID()) AS RandomStudent));

select * from ExamResults;
select * from Student